# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSendsms',
            fields=[
                ('sms_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('captcha', models.CharField(blank=True, max_length=20, null=True)),
                ('device_id', models.CharField(blank=True, max_length=20, null=True)),
                ('is_success', models.CharField(blank=True, max_length=40, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_sendsms',
            },
        ),
    ]
