# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0003_appplatformuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appplatformuser',
            old_name='user_id',
            new_name='user',
        ),
    ]
