# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0004_auto_20160913_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appplatformuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
