# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0005_auto_20160913_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='昵称'),
        ),
    ]
