# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0006_authuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='appplatformuser',
            name='union',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
