# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0007_appplatformuser_union'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appplatformuser',
            old_name='union',
            new_name='unionid',
        ),
    ]
