# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-24 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0003_auto_20160924_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuserprofile',
            name='puser_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='authuser',
            name='is_enterprise',
            field=models.NullBooleanField(verbose_name='是否企业用户'),
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='9fc0caf8825c11e68e93047d7b6f978e', max_length=40, primary_key=True, serialize=False),
        ),
    ]
