# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0004_auto_20160924_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('companyname', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('people_num', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'app_company',
            },
        ),
        migrations.CreateModel(
            name='AppSalesorderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=40, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('insured_city', models.CharField(blank=True, max_length=20, null=True)),
                ('insured_type', models.CharField(blank=True, max_length=20, null=True)),
                ('businesstype', models.CharField(blank=True, max_length=40, null=True)),
                ('socialbase', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('housingfundbase', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('endowment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('medical', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unemployment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('employment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('maternity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('disability', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('housingfund', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('social_startmonth', models.DateTimeField(blank=True, null=True)),
                ('social_endmonth', models.DateTimeField(blank=True, null=True)),
                ('fund_startmonth', models.DateTimeField(blank=True, null=True)),
                ('fund_endmonth', models.DateTimeField(blank=True, null=True)),
                ('mon', models.IntegerField(blank=True, null=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('totalamount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_salesorder_items',
            },
        ),
        migrations.CreateModel(
            name='AppSalesorders',
            fields=[
                ('order_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('paytype', models.CharField(blank=True, max_length=20, null=True)),
                ('clientsource', models.CharField(blank=True, max_length=20, null=True)),
                ('orderstatus', models.IntegerField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
                ('paytime', models.DateTimeField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'app_salesorders',
            },
        ),
        migrations.RenameField(
            model_name='appplatformuser',
            old_name='expirationtime',
            new_name='expiretime',
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='0f0555b0855511e68ddbfcaa1469668c', max_length=40, primary_key=True, serialize=False),
        ),
    ]
