# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0005_auto_20160928_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appplatformuser',
            name='user',
        ),
        migrations.AddField(
            model_name='appplatformuser',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='682814b6860c11e681cdfcaa1469668c', max_length=40, primary_key=True, serialize=False),
        ),
    ]
