# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsendsms',
            name='is_success',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='377d21407a8e11e6ba10047d7b6f978e', max_length=40, primary_key=True, serialize=False),
        ),
    ]
