# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-24 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20160914_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuserprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='appuserprofile',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='9e7bad6c820611e6a8ac047d7b6f978e', max_length=40, primary_key=True, serialize=False),
        ),
    ]
