# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 07:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, max_length=40, null=True, verbose_name='昵称')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='手机')),
                ('avatar', models.CharField(default='', max_length=200, verbose_name='头像')),
                ('is_enterprise', models.NullBooleanField(verbose_name='是否企业用户')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AppCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('companyname', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('people_num', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'app_company',
            },
        ),
        migrations.CreateModel(
            name='AppPlatformUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=40, null=True)),
                ('avatar', models.CharField(blank=True, max_length=200, null=True)),
                ('platform', models.CharField(blank=True, max_length=20, null=True)),
                ('openid', models.CharField(blank=True, max_length=200, null=True)),
                ('unionid', models.CharField(blank=True, max_length=200, null=True)),
                ('access_token', models.CharField(blank=True, max_length=200, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=200, null=True)),
                ('expiretime', models.DateTimeField(blank=True, null=True)),
                ('profileurl', models.CharField(blank=True, max_length=200, null=True)),
                ('ts', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'app_platform_user',
            },
        ),
        migrations.CreateModel(
            name='AppSalesorderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=40, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('insured_city', models.CharField(blank=True, max_length=20, null=True)),
                ('insured_type', models.CharField(blank=True, max_length=20, null=True)),
                ('businesstype', models.CharField(blank=True, max_length=40, null=True)),
                ('socialbase', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('housingfundbase', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('endowment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('medical', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unemployment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('employment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('maternity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('disability', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('housingfund', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('social_startmonth', models.DateTimeField(blank=True, null=True)),
                ('social_endmonth', models.DateTimeField(blank=True, null=True)),
                ('fund_startmonth', models.DateTimeField(blank=True, null=True)),
                ('fund_endmonth', models.DateTimeField(blank=True, null=True)),
                ('mon', models.IntegerField(blank=True, null=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('totalamount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_salesorder_items',
            },
        ),
        migrations.CreateModel(
            name='AppSalesorders',
            fields=[
                ('order_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('paytype', models.CharField(blank=True, max_length=20, null=True)),
                ('clientsource', models.CharField(blank=True, max_length=20, null=True)),
                ('orderstatus', models.IntegerField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
                ('paytime', models.DateTimeField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'app_salesorders',
            },
        ),
        migrations.CreateModel(
            name='AppSendsms',
            fields=[
                ('sms_id', models.CharField(default='39b22318969511e6bee2fcaa1469668c', max_length=40, primary_key=True, serialize=False)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('captcha', models.CharField(blank=True, max_length=20, null=True)),
                ('device_id', models.CharField(blank=True, max_length=20, null=True)),
                ('is_success', models.NullBooleanField()),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'app_sendsms',
            },
        ),
        migrations.CreateModel(
            name='AppUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('puser_id', models.IntegerField(blank=True, null=True, verbose_name='所属用户')),
                ('realname', models.CharField(blank=True, max_length=20, null=True)),
                ('idcart', models.CharField(blank=True, max_length=20, null=True)),
                ('social_province', models.CharField(blank=True, max_length=20, null=True)),
                ('social_city', models.CharField(blank=True, max_length=20, null=True)),
                ('idcart_front', models.CharField(blank=True, max_length=200, null=True)),
                ('idcart_back', models.CharField(blank=True, max_length=200, null=True)),
                ('household_type', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf_account', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'app_user_profile',
            },
        ),
    ]
