# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSocialPrice',
            fields=[
                ('social_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('socialbase_min', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('socialbase_max', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('housingfundbase_min', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('housingfundbase_max', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('endowment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('medical', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unemployment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('employment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('maternity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('disability', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('housingfund', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'app_social_price',
            },
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='65055a069d7a11e6adee047d7b6f978e', max_length=40, primary_key=True, serialize=False),
        ),
    ]
