# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0003_auto_20161029_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='a24a05ca9d7a11e6961e047d7b6f978e', max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appsocialprice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
