# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0005_auto_20161029_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsalesorderitems',
            old_name='fund_endmonth',
            new_name='endmonth',
        ),
        migrations.RenameField(
            model_name='appsalesorderitems',
            old_name='fund_startmonth',
            new_name='startmonth',
        ),
        migrations.RemoveField(
            model_name='appsalesorderitems',
            name='social_endmonth',
        ),
        migrations.RemoveField(
            model_name='appsalesorderitems',
            name='social_startmonth',
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='e6c0f6109f1c11e6b85bfcaa1469668c', max_length=40, primary_key=True, serialize=False),
        ),
    ]
