# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0006_auto_20161031_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='disability',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='employment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='endowment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='housingfund',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='maternity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='medical',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='unemployment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='8b5251ec9f1f11e6a052fcaa1469668c', max_length=40, primary_key=True, serialize=False),
        ),
    ]
