# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0007_auto_20161031_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='createtime',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='createtime',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='fd63a1269f3b11e692a6fcaa1469668c', max_length=40, primary_key=True, serialize=False),
        ),
    ]
