# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0008_auto_20161031_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppSocialPrice',
            new_name='AppSocials',
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='c8ab37e49f3c11e6a344fcaa1469668c', max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='appsocials',
            table='app_socials',
        ),
    ]
