# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0009_auto_20161031_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsalesorders',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='d2f612da9fff11e694cafcaa1469668c', max_length=40, primary_key=True, serialize=False),
        ),
    ]
