# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-05 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0010_auto_20161101_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsalesorders',
            options={'ordering': ['-createtime'], 'verbose_name': '订单', 'verbose_name_plural': '订单管理'},
        ),
        migrations.AlterModelOptions(
            name='appsocials',
            options={'verbose_name': '社保', 'verbose_name_plural': '社保管理'},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='clientsource',
            field=models.CharField(blank=True, choices=[('微信端', 'wechat'), ('web端', 'web')], max_length=20, null=True, verbose_name='客户端来源'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='优惠金额'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='order_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='orderstatus',
            field=models.IntegerField(blank=True, choices=[('未支付', 0), ('已支付', 1), ('已退款', 2)], null=True, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='pay_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='实际支付金额'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='paytime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='paytype',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='支付类型'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='第三方交易号'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='d879c5caa34411e6bf597ce9d3576283', max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appsocials',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='appsocials',
            name='disability',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='残障金'),
        ),
        migrations.AlterField(
            model_name='appsocials',
            name='employment',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='工伤(比例)'),
        ),
        migrations.AlterField(
            model_name='appsocials',
            name='endowment',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='养老(比例)'),
        ),
        migrations.AlterField(
            model_name='appsocials',
            name='housingfund',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='公积金(比例)'),
        ),
        migrations.AlterField(
            model_name='appsocials',
            name='housingfundbase_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='公积金基数(最高)'),
        ),
        migrations.AlterField(
            model_name='appsocials',
            name='housingfundbase_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='公积金基数(最低)'),
        ),
        migrations.AlterField(
            model_name='appsocials',
            name='maternity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='生育(比例)'),
        ),
        migrations.AlterField(
            model_name='appsocials',
            name='medical',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='医疗(比例)'),
        ),
        migrations.AlterField(
            model_name='appsocials',
            name='socialbase_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='社保基数(最高)'),
        ),
        migrations.AlterField(
            model_name='appsocials',
            name='socialbase_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='社保基数(最低)'),
        ),
        migrations.AlterField(
            model_name='appsocials',
            name='type',
            field=models.CharField(blank=True, choices=[('深户第一档', 'shenhu_first'), ('非深户第一档', 'feishenhu_first'), ('非深户第二档', 'feishenhu_second'), ('非深户第三档', 'feishenhu_third')], max_length=20, null=True, verbose_name='社保类型'),
        ),
        migrations.AlterField(
            model_name='appsocials',
            name='unemployment',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='失业(比例)'),
        ),
    ]
