# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0011_auto_20161105_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsalesorders',
            name='clientsource',
            field=models.CharField(blank=True, choices=[('wechat', '微信端'), ('web', 'web端')], max_length=20, null=True, verbose_name='客户端来源'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='createtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='orderstatus',
            field=models.IntegerField(blank=True, choices=[(0, '未支付'), (1, '已支付'), (2, '已退款')], null=True, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='f105915aa3d311e6863a7ce9d3576283', max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appsocials',
            name='type',
            field=models.CharField(blank=True, choices=[('shenhu_first', '深户第一档'), ('feishenhu_first', '非深户第一档'), ('feishenhu_second', '非深户第二档'), ('feishenhu_third', '非深户第三档')], max_length=20, null=True, verbose_name='社保类型'),
        ),
    ]
