# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0012_auto_20161106_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsalesorderitems',
            name='order_id',
        ),
        migrations.AddField(
            model_name='appsalesorderitems',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boai_model.AppSalesorders'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='优惠金额(元)'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='pay_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='实际支付金额(元)'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='paytype',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='appsalesorders',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='总金额(元)'),
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='de2467e6a48f11e697b5fcaa1469668c', max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appsocials',
            name='disability',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='残障金(元)'),
        ),
    ]
