# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0013_auto_20161107_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsalesorders',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='b962fff4a49211e6bfa8fcaa1469668c', max_length=40, primary_key=True, serialize=False),
        ),
    ]
