# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-19 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0015_auto_20161107_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsalesorderitems',
            options={'verbose_name': '订单详情', 'verbose_name_plural': '订单详情列表'},
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='businesstype',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='手续费(元)'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='disability',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='残障金(元)'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='employment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='工伤(元)'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='endmonth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束月份'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='endowment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='养老(元)'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='housingfund',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='公积金(元)'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='housingfundbase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='公积金缴纳基数'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='insured_city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='参保城市'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='insured_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='社保类型'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='maternity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='生育(元)'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='medical',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='医疗(元)'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='mon',
            field=models.IntegerField(blank=True, null=True, verbose_name='月数'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='socialbase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='社保缴纳基数'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='startmonth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='起缴月份'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='totalamount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='总金额(元)'),
        ),
        migrations.AlterField(
            model_name='appsalesorderitems',
            name='unemployment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='失业(元)'),
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='295ca964c5cc11e6a609c03fd5371196', max_length=40, primary_key=True, serialize=False),
        ),
    ]
