# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-19 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boai_model', '0016_auto_20161219_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcompany',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appsendsms',
            name='sms_id',
            field=models.CharField(default='96580f66c5cd11e68a19c03fd5371196', max_length=40, primary_key=True, serialize=False),
        ),
    ]
